### ISSUE TITLE
Didn't blow up

### ISSUE THREAD

**Issue by nordic16** [kaboom-db/kaboom-api#2]
Hey so, I opened this repo because I thought it had some sort of bomb in it (the repo's name is Kaboom, so take a hint)... 

# Fix this, or you're fired!

**Comment by crxssed7** [comment]
What browser are you using?
Whats your user agent?
Is there anything in the console logs?
Whats your IP adress

**Comment by nordic16** [comment]
> What browser are you using? Whats your user agent? Is there anything in the console logs? Whats your IP address?

Hello! I'm using Internet Explorer 1.0!
User agent? I use Linux, no 3-letter agencies can spot me.
Console logs? Nah, I haven't touched on any of my consoles in a while...
My IP address? 127.0.0.1!
